/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListViewPanel.java
 *
 * Created on 14 févr. 2011, 17:46:11
 */

package org.demo.filebrowser.explorer.view;

import java.io.File;

/**
 *
 * @author ECO
 */
public class ListViewPanel extends javax.swing.JPanel {

    /** Creates new form ListViewPanel */
    public ListViewPanel(String caption) {
        initComponents();
        actionNameLabel.setText(caption);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionNameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        actionNameLabel.setText(org.openide.util.NbBundle.getMessage(ListViewPanel.class, "ListViewPanel.actionNameLabel.text")); // NOI18N
        add(actionNameLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionNameLabel;
    // End of variables declaration//GEN-END:variables

}
